export const NAME = 'alphaCalculator';

export const SET_ALPHA_VALUE = 'SET_ALPHA_VALUE';

export const REQUEST_ALPHA_CALCULATIONS = 'REQUEST_ALPHA_CALCULATIONS';
export const SUCCESS_ALPHA_CALCULATIONS = 'SUCCESS_ALPHA_CALCULATIONS';
export const FAIL_ALPHA_CALCULATIONS = 'FAIL_ALPHA_CALCULATIONS';

export const NULLIFY_ALPHA_CALCULATION = 'NULLIFY_ALPHA_CALCULATION';
